services:
  id_index_api:
      init: true
      build:
        context: ./idIndexApi/
        dockerfile: ./Dockerfile
      container_name: id_index_api
      ports:
        - "3012:3012"
      restart: always
      volumes:
        - ${id_index_api__vol__data:-id_index_api__data}:/home/node/idIndexApi/data:rw
        - ${id_index_api__vol__src:-id_index_api__src}:/home/node/idIndexApi/src:ro
      networks:
        - ereuse

  blockchain_test_node:
      init: true
      build:
        context: ./
        dockerfile: ./Dockerfile_blockchain_test_node
      container_name: blockchain_test_node
      ports:
        - "8545:8545"
      restart: always
      networks:
        - ereuse

  api_connector:
      init: true
      build: ./
      depends_on:
        - id_index_api
        - blockchain_test_node
        - veramo_api
      container_name: api_connector
      ports:
        - "3010:3010"
      restart: always
      volumes:
        - ${api_connector__vol__src:-api_connector__api_src}:/home/node/app/src:rw
        - ${api_connector__vol__shared:-api_connector__shared_src}:/home/node/app/shared:rw
        - ./.env:/home/node/app/.env:ro
      networks:
        - ereuse

  did_resolver:
      init: true
      build:
        context: ./
        dockerfile: ./didResolverApi/Dockerfile
      container_name: did_resolver
      ports:
        - "3011:3011"
      restart: always
      volumes:
        - ${did_resolver__vol__api_src:-did_resolver__api_src}:/home/node/didResolverAPI/src:rw
        - ${did_resolver__vol__module_src:-did_resolver__module_src}:/home/node/didResolverModule/src:rw
        - ./.env:/home/node/didResolverAPI/src/.env:ro
      networks:
        - ereuse

  dpp_indexer:
      init: true
      build:
        context: ./
        dockerfile: ./observerModule/Dockerfile
      depends_on:
        - api_connector
      container_name: dpp_indexer # name of the built image
      environment:
        - HTTP_PORT=3014
      ports:
        - "3014:3014"
      restart: always
      volumes:
        - ${dpp_indexer__vol__data:-dpp_indexer__data}:/home/node/observerModule/data:rw
        - ${dpp_indexer__vol__src:-dpp_indexer__src}:/home/node/observerModule/src:ro
        - ${dpp_indexer__vol__shared:-dpp_indexer__shared}:/home/node/observerModule/shared:rw
        - ./.env:/home/node/observerModule/src/.env:ro
      networks:
        - ereuse

  veramo_api:
      init: true
      build:
        context: ./veramoApi
        dockerfile: ./Dockerfile
      container_name: veramo_api # name of the built image
      ports:
        - "3016:3016"
      restart: always
      volumes:
        - ${veramo_api__vol__src:-veramo_api__src}:/home/node/veramoApi/src:rw
      networks:
        - ereuse

networks:
    ereuse:
      driver: bridge

volumes:
  id_index_api__data:
  id_index_api__src:
  api_connector__api_src:
  api_connector__shared_src:
  did_resolver__api_src:
  did_resolver__module_src:
  dpp_indexer__data:
  dpp_indexer__src:
  dpp_indexer__shared:
  veramo_api__src:
