apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tfg-ereuse-dpp.fullname" . }}-{{ .Values.devicehub.name }}-config
  labels:
    {{- include "tfg-ereuse-dpp.labels" . | nindent 4 }}
data:
 {{- range $key, $value := .Values.devicehub.config }}
 {{ $key }}: {{ $value | quote }}
 {{- end }}
 DOMAIN: {{ .Values.global.domain }}
 #ALLOWED_HOSTS: localhost,localhost:8000,127.0.0.1,{{ .Values.global.domain }},{{ .Values.global.domain }}:8000
 ALLOWED_HOSTS: "['*']"
