apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tfg-ereuse-dpp.fullname" . }}-{{ .Values.devicehub.name }}-configmap
  labels:
    {{- include "tfg-ereuse-dpp.labels" . | nindent 4 }}
data:
 {{- range $key, $value := .Values.devicehub.config }}
 {{ $key }}: {{ $value | quote }}
 {{- end }}