apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tfg-ereuse-dpp.fullname" . }}-{{ .Values.dppIndexer.name }}
  labels:
    {{- include "tfg-ereuse-dpp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dppIndexer.replicaCount }}
  selector:
    matchLabels:
      {{- include "tfg-ereuse-dpp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.dppIndexer.name }}
  template:
    metadata:
      labels:
        {{- include "tfg-ereuse-dpp.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.dppIndexer.name }}
    spec:
      containers:
        - name: id-index-api
          image: "{{ .Values.dppIndexer.image.repository }}:{{ .Values.dppIndexer.image.tag }}"
          imagePullPolicy: {{ .Values.dppIndexer.image.pullPolicy | default .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.dppIndexer.service.port }}
              name: http
          env:
            - name: HTTP_PORT
              value: "{{ .Values.dppIndexer.service.port }}"
          envFrom:
            - configMapRef:
                name: {{ include "tfg-ereuse-dpp.fullname" . }}-shared-config
          livenessProbe:
            httpGet:
              path: {{ .Values.dppIndexer.healthcheck.path }}
              port: {{ .Values.dppIndexer.service.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.dppIndexer.healthcheck.path }}
              port: {{ .Values.dppIndexer.service.port }}
          volumeMounts:
            - name: shared-storage
              mountPath: /home/node/observerModule/shared
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Values.global.sharedStorage.name }}