{{- if .Values.dppIndexer.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tfg-ereuse-dpp.fullname" . }}-{{ .Values.dppIndexer.name }}
  labels:
    {{- include "tfg-ereuse-dpp.labels" . | nindent 4 }}
  {{- with .Values.dppIndexer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.global.domain }}
spec:
  {{- with .Values.dppIndexer.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.dppIndexer.ingress.tls }}
  tls:
    {{- range .Values.dppIndexer.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.dppIndexer.name }}-{{ $.Values.global.domain }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "tfg-ereuse-dpp.fullname" $ }}-{{ $.Values.dppIndexer.name }}
                port:
                  number: {{ $.Values.dppIndexer.service.port }}
{{- end }}