# .github/workflows/id-index-api-ci-cd.yaml
name: id-index-api CI/CD
on:
  push:
    branches: [ main ]
    paths:
      - 'idIndexApi/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image_name: tfg-ereuse-dpp/id-index-api
      context_path: ./idIndexApi
      dockerfile_path: ./idIndexApi/Dockerfile