version: '3'
services:
  api: 
    build: ./
    container_name: fuzzySearchEngine # name of the built image
    ports:
      - "80:3000"
    restart: always
    volumes:
      - ./src:/home/node/searchEngine/src:ro
      - ./public:/home/node/searchEngine/public:ro
