version: '3'
services:
  api: 
    build: ./
    container_name: fuzzySearchEngine # name of the built image
    ports:
      - "3013:3013"
    restart: always
    volumes:
      - ./src:/home/node/searchEngine/src:ro
