apiVersion: v2
name: ereuse-dpp
description: Solidity smart contracts developed to manage electronic devices and its Product Passport and an API that can call a IOTA L2 DLT with smart contracts.
type: application
version: 0.1.0
appVersion: "1.16.0"
