version: '3'
services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: searchEngine
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./web/index.html:/var/www/index.html:rw
