apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tfg-ereuse-dpp.fullname" . }}-shared-config
  labels:
    {{- include "tfg-ereuse-dpp.labels" . | nindent 4 }}
data:
 {{- range $key, $value := .Values.config }}
 {{ $key }}: {{ $value | quote }}
 {{- end }}
 NODE_IP: "http://{{ .Release.Name }}-{{ .Values.blockchainNode.name }}"
 ID_INDEX: "http://{{ .Release.Name }}-{{ .Values.idIndexApi.name }}:{{ .Values.idIndexApi.service.port }}"
 VERAMO_URL: "http://{{ .Release.Name }}-veramo-api:{{ .Values.veramoApi.service.port }}"
 API_CONNECTOR_URL: "http://{{ .Release.Name }}-{{ .Values.apiConnector.name }}:{{ .Values.apiConnector.service.port }}"
 API_DLT: "http://{{ .Release.Name }}-{{ .Values.apiConnector.name }}:{{ .Values.apiConnector.service.port }}"
 API_RESOLVER: "http://{{ .Release.Name }}-{{ .Values.idIndexApi.name }}:{{ .Values.idIndexApi.service.port }}"
 ID_FEDERATED: {{ .Values.config.ID_FEDERATED }}
 API_DLT_TOKEN: {{ .Values.config.API_DLT_TOKEN }}