apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tfg-ereuse-dpp.fullname" . }}-configmap
  labels:
    {{- include "tfg-ereuse-dpp.labels" . | nindent 4 }}
data:
 {{- range $key, $value := .Values.config }}
 {{ $key }}: {{ $value | quote }}
 {{- end }}
 NODE_IP: "{{ .Release.Name }}-{{ .Values.blockchainNode.name }}"
 ID_INDEX: "http://{{ .Release.Name }}-{{ .Values.idIndexApi.name }}:{{ .Values.idIndexApi.service.port }}"
 VERAMO_URL: "http://{{ .Release.Name }}-veramo-api:{{ .Values.veramoApi.service.port }}"
 API_CONNECTOR_URL: "http://{{ .Release.Name }}-{{ .Values.apiConnector.name }}:{{ .Values.apiConnector.service.port }}"