apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tfg-ereuse-dpp.fullname" . }}-configmap
  labels:
    {{- include "tfg-ereuse-dpp.labels" . | nindent 4 }}
data:
  MINING_INTERVAL: "{{ .Values.config.miningInterval }}"