# Shared Storage for the DPP

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.sharedStorage.name }}
  # Ensure that the PVC is deleted after the rest of the resources
  finalizers:
    - kubernetes.io/pvc-protection
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # Size doesn't matter for EFS but is required by Kubernetes
  storageClassName: {{ .Values.global.sharedStorage.className }}