global:
  domain: ereuse-dpp.ajripa.click
idIndexApi:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/id-index-api"
    tag: "sha-dd273d23e7681f0155c1ff4a037a1d84837802ab"
blockchainNode:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/blockchain-node"
    tag: "sha-dd273d23e7681f0155c1ff4a037a1d84837802ab"
apiConnector:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/api-connector"
    tag: "sha-dd273d23e7681f0155c1ff4a037a1d84837802ab"
veramoApi:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/veramo-api"
    tag: "sha-dd273d23e7681f0155c1ff4a037a1d84837802ab"
didResolver:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/did-resolver"
    tag: "sha-dd273d23e7681f0155c1ff4a037a1d84837802ab"
dppIndexer:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/dpp-indexer"
    tag: "sha-dd273d23e7681f0155c1ff4a037a1d84837802ab"
  ingress:
    enabled: true
    className: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: shared-public
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: '3014'
devicehub:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/device-hub"
    tag: "sha-dd273d23e7681f0155c1ff4a037a1d84837802ab"
  config:
    DEMO: true
  ingress:
    enabled: true
    className: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: shared-public
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: '8000'
      alb.ingress.kubernetes.io/healthcheck-path: /login/
search:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/search"
    tag: "sha-dd273d23e7681f0155c1ff4a037a1d84837802ab"
  ingress:
    enabled: true
    className: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: shared-public
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: '3000'
createOperatorUser:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/create-operator-user"
    tag: "sha-dd273d23e7681f0155c1ff4a037a1d84837802ab"
