idIndexApi:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/id-index-api"
    tag: "latest"

blockchainNode:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/blockchain-node"
    tag: "latest"

apiConnector:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/api-connector"
    tag: "latest"

veramoApi:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/veramo-api"
    tag: "latest"

didResolver:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/did-resolver"
    tag: "latest"

dppIndexer:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/dpp-indexer"
    tag: "latest"

devicehubDjango:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/devicehub-django"
    tag: "latest"
  config:
    DOMAIN: ereuse-dpp.ajripa.click
  ingress:
    enabled: true
    className: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: shared-public
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: '8000'
    external-dns.alpha.kubernetes.io/hostname: ereuse-dpp.ajripa.click
    hosts:
      - host: ereuse-dpp.ajripa.click
        paths:
        - path: /*
          pathType: ImplementationSpecific

