global:
  domain: ereuse-dpp.ajripa.click
idIndexApi:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/id-index-api"
    tag: "sha-c6b1895a01253178172c13f5f9f028023d4ad58b"
blockchainNode:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/blockchain-node"
    tag: "latest"
apiConnector:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/api-connector"
    tag: "sha-9c7b4f5151e2ef378943eebfddc528642bb578ad"
veramoApi:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/veramo-api"
    tag: "latest"
didResolver:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/did-resolver"
    tag: "latest"
dppIndexer:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/dpp-indexer"
    tag: "latest"
  ingress:
    enabled: true
    className: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: shared-public
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: '3014'
devicehub:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/devicehub"
    tag: "latest"
  config:
    DEMO: true
  ingress:
    enabled: true
    className: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: shared-public
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: '8000'
      alb.ingress.kubernetes.io/healthcheck-path: /login/
search:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/search"
    tag: "latest"
  ingress:
    enabled: true
    className: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/group.name: shared-public
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: '3000'
createOperatorUser:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/create-operator-user"
    tag: "latest"
