global:
  domain: ereuse-dpp.ajripa.click

idIndexApi:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/id-index-api"
    tag: "latest"

blockchainNode:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/blockchain-node"
    tag: "latest"

apiConnector:
  image:
    repository: "ghcr.io/ajripa-uoc/tfg-ereuse-dpp/api-connector"
    tag: "latest"

veramoApi:
  image:
    repositor