apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tfg-ereuse-dpp.fullname" . }}-{{ .Values.idIndexApi.name }}
  labels:
    {{- include "tfg-ereuse-dpp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.idIndexApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "tfg-ereuse-dpp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.idIndexApi.name }}
  template:
    metadata:
      labels:
        {{- include "tfg-ereuse-dpp.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.idIndexApi.name }}
    spec:
      containers:
        - name: {{ .Values.idIndexApi.name }}
          image: "{{ .Values.idIndexApi.image.repository }}:{{ .Values.idIndexApi.image.tag }}"
          imagePullPolicy: {{ .Values.idIndexApi.image.pullPolicy | default .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.idIndexApi.service.port }}
              name: http
          livenessProbe:
            httpGet:
              path: {{ .Values.idIndexApi.healthcheck.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.idIndexApi.healthcheck.path }}
              port: http
