# .github/workflows/docker-build-template.yml
name: "Template: Docker Build and Push"

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the Docker image'
        required: true
        type: string
      context_path:
        description: 'Path to the Docker context'
        required: true
        type: string
      dockerfile_path:
        description: 'Path to the Dockerfile'
        required: true
        type: string
      push_enabled:
        description: 'Whether to push the image'
        required: false
        type: boolean
        default: true
      registry:
        description: 'Docker registry'
        required: false
        type: string
        default: 'ghcr.io'
    outputs:
      image_full_name:
        description: "Full repository name including registry"
        value: ${{ jobs.build-and-push.outputs.image_full_name }}
      sha_tag:
        description: "SHA tag"
        value: ${{ jobs.build-and-push.outputs.sha_tag }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build - ${{ inputs.image_name }}

    permissions:
      contents: read
      packages: write
      id-token: write

    outputs:
      image_full_name: ${{ steps.extract_info.outputs.image_full_name }}
      sha_tag: ${{ steps.extract_info.outputs.sha_tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image_name }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Extract image info
        id: extract_info
        run: |
          # Get the full repository name
          echo "image_full_name=$(echo '${{ steps.meta.outputs.tags }}' | head -n 1 | cut -d':' -f1)" >> $GITHUB_OUTPUT
          # Get the SHA tag
          echo "sha_tag=$(echo '${{ steps.meta.outputs.tags }}' | grep 'sha-' | cut -d':' -f2)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context_path }}
          file: ${{ inputs.dockerfile_path }}
          push: ${{ inputs.push_enabled }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max