# .github/workflows/id-index-api-ci-cd.yaml
name: CI/CD id-index-api
on:
  push:
    branches: [ main ]
    paths:
      - 'idIndexApi/**'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    name: CI
    uses: ./.github/workflows/docker-build-template.yaml
    with:
      image_name: tfg-ereuse-dpp/id-index-api
      context_path: ./idIndexApi
      dockerfile_path: ./idIndexApi/Dockerfile

  deploy:
    name: CD
    needs: build
    uses: ./.github/workflows/update-helm-template.yaml
    with:
      chart_name: tfg-ereuse-dpp
      service_name: idIndexApi
      image_tag: ${{ needs.build.outputs.sha_tag }}
      repo_name: ${{ needs.build.outputs.image_full_name }}
      force_argocd_sync: true