# .github/workflows/update-helm-template.yml
name: Update Helm Chart Template

on:
  workflow_call:
    inputs:
      chart_name:
        description: 'Name of the Helm chart'
        required: true
        type: string
      service_name:
        description: 'Name of the service'
        required: true
        type: string
      image_tag:
        description: 'Docker image tag'
        required: true
        type: string
      repo_name:
        description: 'Repository name'
        required: true
        type: string

jobs:
  update-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update values-tfg.yaml
        env:
          REPO_NAME: ${{ inputs.repo_name }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          CHART_NAME: ${{ inputs.chart_name }}
          SERVICE_NAME: ${{ inputs.service_name }}
        run: |
          cd chart/${CHART_NAME}
          # Update repository and tag using yq
          yq -i e ".$SERVICENAME.image.repository = \"$REPO_NAME\"" values-tfg.yaml
          yq -i e ".$SERVICENAME.image.tag = \"$IMAGE_TAG\"" values-tfg.yaml

          # Verify changes
          cat values-tfg.yaml

      - name: Commit and push changes
        env:
          COMMIT_MESSAGE: "gitops: image tag ${{ inputs.image_tag }} and network url ${{ inputs.network_url }}"
          CHART_NAME: ${{ inputs.chart_name }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git pull
          git push